source 'https://rubygems.org'
 
# Needed by heroku
ruby '2.2.0'
 
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
 
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
 
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
 
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
 
gem 'sorcery'
 
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
 
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
 
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
 
# Heroku production settings
group :production do
  gem 'pg'
  gem 'rails_12factor'
end
 
group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end
 
# Development settings
group :development do
  gem 'mailcatcher'
end
 
# Development and test settings
group :development, :test do
  gem 'rspec-rails'
  gem 'sqlite3'
  gem 'foreman'
  gem 'quiet_assets'
end
 
group :test do
  gem 'launchy'
  gem 'factory_girl_rails', require: false
  gem 'database_cleaner'
  gem 'capybara-email'
end